#!/bin/bash
########### BASH COMPLETION Section ###########
##### Check if 'complete' command is available #####
command -v complete >/dev/null
if [ "${?}" -eq 0 ] ;then
  
  ### Set 'kubectl' command completion for BASH and also make it work with the 'k' command alias.
  command -v kubectl >/dev/null && \
    source <(kubectl completion bash) && \
    alias k="kubectl" && \
    complete -F __start_kubectl k && \
    export do='--dry-run=client -o yaml'
  
  ### For 'aws' command auto completion
  _aws_completer_path=$(which aws_completer)
  if [ "${_aws_completer_path}" == '' ] ;then
    :
  else
    complete -C "${_aws_completer_path}" aws
  fi
  
  ### For 'helm' command auto completion
  command -v helm >/dev/null && \
  source <(helm completion bash)

fi
